name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: Lint
        run: PYTHONPATH=src uv run pylint src
      - run: uv sync --group dev   # install package + dev deps
      - run: uv run pytest
